[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]

solc_version = "0.8.19"
evm_version = "paris"

optimizer = true
optimizer_runs = 2000
via_ir = false